require("plugins")
require("core/options")
require("core/autocmds")
require("core/statusline")
require("core/keymaps")
require("plugins/nvim-tree")
require("plugins/indent-blankline")
require("plugins/coc-nvim")
